/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_windowEspaceAdmin (void);
GtkWidget* create_windowEspaceDonneur (void);
GtkWidget* create_Supprimer_window (void);
GtkWidget* create_administrateur_window (void);
